### ISSUE TITLE
Add to applications

### ISSUE THREAD

**Issue by domoritz** [gjmcn/to-vega#4]
this looks awesome. Do you want to add a link to to-vega at https://vega.github.io/vega-lite/applications.html? Just send us a PR.

**Comment by domoritz** [comment]
Btw, did you see https://github.com/vega/vega-lite/issues/2280 and create this library then?

**Comment by gjmcn** [comment]
Great, I have sent a PR.

I looked at Altair, but missed [vega/vega-lite#2280](https://github.com/vega/vega-lite/issues/2280) - so thanks for bringing it to my attention!
